version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    networks:
      - app-network
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
