"""new initial migration with all changes

Revision ID: 254a5b0cbac2
Revises: 
Create Date: 2024-11-21 20:28:54.858361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "254a5b0cbac2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_logs_id"), "action_logs", ["id"], unique=False
    )
    op.create_table(
        "insurance_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "cargo_type",
            sa.Enum("GLASS", "METAL", "WOOD", "OTHER", name="cargotype"),
            nullable=False,
        ),
        sa.Column("declared_value", sa.Float(), nullable=False),
        sa.Column("insurance_cost", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insurance_requests_id"),
        "insurance_requests",
        ["id"],
        unique=False,
    )
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "cargo_type",
            sa.Enum("GLASS", "METAL", "WOOD", "OTHER", name="cargotype"),
            nullable=False,
        ),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tariffs_cargo_type"), "tariffs", ["cargo_type"], unique=False
    )
    op.create_index(op.f("ix_tariffs_id"), "tariffs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tariffs_id"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_cargo_type"), table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index(
        op.f("ix_insurance_requests_id"), table_name="insurance_requests"
    )
    op.drop_table("insurance_requests")
    op.drop_index(op.f("ix_action_logs_id"), table_name="action_logs")
    op.drop_table("action_logs")
    # ### end Alembic commands ###
